site_name: SB Docs
site_url: https://securityboat.github.io/csm
site_author: Himanshu Gupta
site_description: >-
  This is SecurityBoat Workbook description.

# Copyright
copyright: Copyright @ 2024 SecurityBoat Cybersecurity Solution Private Limited

# Configuration
theme:
  name: material